owner: aspyn-io
repo: status

sites:
  - name: Home
    url: https://aspyn.io
  - name: UI
    url: https://aptive.aspyn.io
  - name: Auth
    url: https://account.aspyn.io
  - name: Admin
    url: https://api.aptive.aspyn.io/admin/v1/healthz
  - name: CRM
    url: https://api.aptive.aspyn.io/crm/v1/docs/api/
  - name: Pay
    url: https://api.aptive.aspyn.io/pay/v1/docs/api/
  - name: Field Service
    url: https://api.aptive.aspyn.io/field-service/v1/docs/api/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.aspyn.io
  # baseUrl: /your-repo-name
  logoUrl: https://avatars.githubusercontent.com/u/180470179?s=200&v=4
  name: Aspyn Status
  introTitle: "**Aspyn Status Page** - Monitoring Your Services in Real-Time"
  introMessage: >
    Welcome to the Aspyn Status page. Here, you can find real-time updates and historical uptime information for our services. For more information, visit our [GitHub repository](https://github.com/upptime/upptime).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
