owner: aspyn-io
repo: status

sites:
  - name: Homepage
    url: https://aspyn.io
    icon: https://aptive.aspyn.io/favicon.ico
    assignees:
      - syntaqx
  - name: UI
    url: https://aptive.aspyn.io/healthz
    icon: https://aptive.aspyn.io/favicon.ico
    assignees:
      - syntaqx
  # Disabled because of GitHub Pages, these are 404s
  # - name: Customer Portal
  #   url: https://app.aspyn.io/healthz
  #   assignees:
  #     - syntaqx
  # - name: Mobile
  #   url: https://mobile.aspyn.io/healthz
  #   assignees:
  #     - syntaqx
  - name: Auth
    url: https://account.aspyn.io
    assignees:
      - bblaker
  - name: Admin
    url: https://api.aptive.aspyn.io/admin/v1/healthz
    __dangerous__body_down_if_text_missing: '"status":"OK"'
    assignees:
      - syntaqx
  - name: Communications
    url: https://api.aptive.aspyn.io/communications/v1/up
    assignees:
      - syntaqx
  - name: CRM
    url: https://api.aptive.aspyn.io/crm/v1/up
    assignees:
      - john-peterson-g17
  - name: Pay
    url: https://api.aptive.aspyn.io/pay/v1/up
    icon: https://api.aptive.aspyn.io/pay/v1/favicon-32x32.png
    assignees:
      - john-peterson-g17
  - name: Field Service
    url: https://api.aptive.aspyn.io/field-service/v1/up
    assignees:
      - jonmccutchan90
  - name: Sales
    url: https://api.aptive.aspyn.io/sales/v1/up
    assignees:
      - syntaqx
  - name: Blog
    url: https://blog.aspyn.io
    assignees:
      - john-peterson-g17
  - name: Customer Portal
    url: https://app.aspyn.io
    assignees:
      - john-peterson-g17
  - name: VROOM
    url: https://api.aptive.aspyn.io/vroom/v1/health
    assignees:
      - IHaveASegway
  - name: ORS (OpenRouteService)
    url: https://api.aptive.aspyn.io/ors/v2/health
    assignees:
      - IHaveASegway

status-website:
  cname: status.aspyn.io
  logoUrl: https://avatars.githubusercontent.com/u/180470179?s=200&v=4
  favicon: https://aptive.aspyn.io/favicon.ico
  name: Aspyn Status
  introTitle: "**Aspyn Status Page**"
  introMessage: >
    Welcome to the Aspyn Status page. Here, you can find real-time updates and historical uptime information for our services. For more information, visit our [GitHub repository](https://github.com/upptime/upptime).
  navbar:
    - title: Aspyn.io
      href: https://aspyn.io
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

user-agent: aspyn-io

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
