owner: aspyn-io
repo: status

sites:
  - name: UI
    url: https://aptive.aspyn.io
    assignees:
      - syntaqx
  - name: Auth
    url: https://account.aspyn.io
    assignees:
      - bblaker
  - name: Admin
    url: https://api.aptive.aspyn.io/admin/v1/healthz
    __dangerous__body_down_if_text_missing: '"status":"OK"'
    assignees:
      - syntaqx
  - name: CRM
    url: https://api.aptive.aspyn.io/crm/v1/healthz
    __dangerous__body_down_if_text_missing: '"status":"OK"'
    assignees:
      - john-peterson-g17
  - name: Pay
    url: https://api.aptive.aspyn.io/pay/v1/healthz
    __dangerous__body_down_if_text_missing: '"status":"OK"'
    assignees:
      - john-peterson-g17
  - name: Field Service
    url: https://api.aptive.aspyn.io/field-service/v1/healthz
    __dangerous__body_down_if_text_missing: '"status":"OK"'
    assignees:
      - jonmccutchan90
  - name: Blog
    url: https://blog.aspyn.io
    assignees:
      - john-peterson-g17
  - name: Portal
    url: https://app.aspyn.io
    assignees:
      - john-peterson-g17

status-website:
  cname: status.aspyn.io
  # baseUrl: /your-repo-name
  logoUrl: https://avatars.githubusercontent.com/u/180470179?s=200&v=4
  name: Aspyn Status
  introTitle: "**Aspyn Status Page**"
  introMessage: >
    Welcome to the Aspyn Status page. Here, you can find real-time updates and historical uptime information for our services. For more information, visit our [GitHub repository](https://github.com/upptime/upptime).
  navbar:
    - title: Aspyn.io
      href: https://aspyn.io
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
